# Generated by Django 4.1.5 on 2023-01-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campo',
            new_name='Campu',
        ),
    ]
